SHOW TABLES;

USE PORTFOLIODB;

CREATE TABLE BBS (
       BBSID INT NOT NULL,
       BBSTITLE VARCHAR(80),
       BBSCONTENT VARCHAR(1000),
       BBSDATE TIMESTAMP DEFAULT NOW(),
       BBSHIT INT,
       BBSNAME VARCHAR(50) NOT NULL,
       BBSEMAIL VARCHAR(50) NOT NULL,
       BBSPHONE VARCHAR(20),
       ID VARCHAR(50), 
       PRIMARY KEY (BBSID)
)default CHARSET=utf8;

select * from BBS;
desc BBS;
drop table BBS;